"""add weather forecast table

Revision ID: 9b436d770562
Revises: a32ef279a85a
Create Date: 2025-12-18 23:48:32.414706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b436d770562'
down_revision: Union[str, Sequence[str], None] = 'a32ef279a85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_created_at'), 'weather_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_forecast_datetime'), 'weather_forecasts', ['forecast_datetime'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_id'), 'weather_forecasts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecasts_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_datetime'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_created_at'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
