"""add custom_name to devices

Revision ID: a32ef279a85a
Revises: debd1177d37b
Create Date: 2025-12-03 23:43:35.384976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32ef279a85a'
down_revision: Union[str, Sequence[str], None] = 'debd1177d37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('custom_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'custom_name')
    # ### end Alembic commands ###
